"""Unit tests for OngTSDB that don't require a running server."""

import threading
import time
from unittest.mock import patch

import numpy as np
import pytest

from ong_tsdb import CHUNK_ROWS, DTYPE
from ong_tsdb.database import OngTSDB, InvalidDataWriteException

WRITE = "write"
READ = "read"


@pytest.fixture
def db(tmp_path):
    """Fresh OngTSDB rooted in tmp_path with one test db and sensor.

    The admin key is auto-generated by OngTSDB.__init__ when bootstrapping a
    new database, so we read it back from the config file.
    """
    d = OngTSDB(path=str(tmp_path))
    with open(d.FU.path_config()) as f:
        admin = f.readline().strip()
    d.create_db(admin, "test")
    d.create_sensor(admin, "test", "s1", "1s", WRITE, READ, ["m1", "m2"])
    # Stash the admin key on the fixture so tests can use it
    d._admin_key = admin
    return d


def _admin(db):
    return db._admin_key


def _now():
    return float(time.time())


def test_write_tick_numpy_without_timestamps(db):
    # Bug 1.4: previously crashed with "tuple object is not callable" because
    # np_timestamps defaulted to a 2D array that was then indexed as 1D.
    # With a single-row array the new code creates a 1D timestamp vector.
    np_values = np.array([[1.0, 2.0]], dtype=np.float32)
    db.write_tick_numpy(WRITE, "test", "s1", np_values, np_timestamps=None)
    dates, values = db.read(READ, "test", "s1", start_ts=0, end_ts=_now() + 10)
    assert dates is not None
    assert values.shape[0] >= 1


def test_write_tick_numpy_refuses_corrupt_chunk(db, tmp_path):
    # Write a valid value first so the chunk exists
    db.write_tick_numpy(
        WRITE,
        "test",
        "s1",
        np.array([[1.0, 2.0]], dtype=DTYPE),
        np_timestamps=np.array([_now() + 1]),
    )
    # Locate the chunk
    chunks = db.FU.getchunks("test", "s1")
    assert chunks
    chunk_path = db.FU.path("test", "s1", chunks[0])

    # Corrupt it: 16 bytes short
    raw = open(chunk_path, "rb").read()
    with open(chunk_path, "wb") as f:
        f.write(raw[: len(raw) - 16])

    with pytest.raises(
        InvalidDataWriteException, match="Refusing to overwrite corrupt chunk"
    ):
        db.write_tick_numpy(
            WRITE,
            "test",
            "s1",
            np.array([[5.0, 6.0]], dtype=DTYPE),
            np_timestamps=np.array([_now() + 1]),
        )


def test_read_iter_skips_corrupt_chunk(db, tmp_path):
    # Write some data in two different chunks (use timestamps spaced > 1 chunk)
    chunker = db.get_chunker(READ, "test", "s1")
    chunk_duration = chunker.chunk_duration
    now = _now()
    # Force the chunk alignment to a clean boundary
    start_ts = chunker.chunk_timestamp(now)
    db.write_tick_numpy(
        WRITE,
        "test",
        "s1",
        np.array([[1.0, 2.0]], dtype=DTYPE),
        np_timestamps=np.array([start_ts + 0.1]),
    )
    db.write_tick_numpy(
        WRITE,
        "test",
        "s1",
        np.array([[3.0, 4.0]], dtype=DTYPE),
        np_timestamps=np.array([start_ts + chunk_duration + 0.1]),
    )

    chunks = db.FU.getchunks("test", "s1")
    assert len(chunks) >= 2
    # Corrupt the SECOND chunk
    second = db.FU.path("test", "s1", chunks[1])
    raw = open(second, "rb").read()
    with open(second, "wb") as f:
        f.write(raw[: len(raw) - 16])

    # The read should succeed: it skips the corrupt chunk, returns data
    # from the good one, and logs the error (visible in caplog if needed).
    dates, values = db.read(
        READ, "test", "s1", start_ts=0, end_ts=now + 2 * chunk_duration
    )
    assert dates is not None
    assert values.shape[0] >= 1  # at least the first row survived


def test_read_iter_cache_cleanup_on_abort(db):
    """After the consumer closes the generator, the cache entry must be gone."""
    db.write_tick_numpy(
        WRITE,
        "test",
        "s1",
        np.array([[1.0, 2.0]], dtype=DTYPE),
        np_timestamps=np.array([_now() + 1]),
    )
    gen = db.read_iter(READ, "test", "s1", 0, _now() + 1e9)
    next(gen)  # start iterating; populates the cache
    assert len(db._cache) == 1
    gen.close()
    # Give the background thread a moment to potentially run
    time.sleep(0.05)
    assert len(db._cache) == 0


def test_concurrent_writes_no_corruption(tmp_path):
    """Multiple writers + one metric extender must not corrupt the chunks.

    The 'Invalid number of cols' error is a legitimate race (the extender
    is mid-rewrite when the writer tries to push the old column count).
    We tolerate it -- the real assertion is that no chunk file ends up
    with a corrupt size or an inconsistent checksum.
    """
    d = OngTSDB(path=str(tmp_path))
    with open(d.FU.path_config()) as f:
        admin = f.readline().strip()
    d.create_db(admin, "test")
    d.create_sensor(admin, "test", "s1", "1s", WRITE, READ, ["m1"])

    unexpected_errors = []
    n_per_writer = 30

    def writer(seed):
        for i in range(n_per_writer):
            try:
                d.write_tick_numpy(
                    WRITE,
                    "test",
                    "s1",
                    np.array([[float(seed * 1000 + i)]], dtype=DTYPE),
                    np_timestamps=np.array(
                        [_now() + i + seed * 1e-3], dtype=np.float64
                    ),
                )
            except InvalidDataWriteException:
                pass  # legitimate race with the extender
            except Exception as e:
                unexpected_errors.append(("writer", e))

    def extender():
        time.sleep(0.02)
        try:
            d.add_new_metrics(admin, "test", "s1", ["m2"], fill_value=np.nan)
        except Exception as e:
            unexpected_errors.append(("extender", e))

    threads = [threading.Thread(target=writer, args=(i,)) for i in range(4)]
    threads.append(threading.Thread(target=extender))
    for t in threads:
        t.start()
    for t in threads:
        t.join()

    assert not unexpected_errors, f"Unexpected errors: {unexpected_errors}"

    # Verify chunks are still parseable and checksums are consistent.
    for sensor in d.FU.getsensors("test"):
        for cf in d.FU.getchunks("test", sensor):
            path = d.FU.path("test", sensor, cf)
            arr = d.FU.fast_read_np(path)
            if arr is None or arr.shape[0] == 0:
                continue
            # Unwritten rows are NaN; match the read path's filter.
            used = arr[:, 0] > 0
            if not used.any():
                continue
            v = arr[used, 1:-1]
            expected = np.nansum(v, axis=1)
            np.testing.assert_allclose(
                arr[used, -1], expected, atol=1e-3, err_msg=f"in {path}"
            )


def test_get_sensor_lock_returns_same_lock(db):
    a = db._get_sensor_lock("test", "s1")
    b = db._get_sensor_lock("test", "s1")
    c = db._get_sensor_lock("test", "other")
    assert a is b
    assert a is not c


def test_add_new_metrics_uses_per_sensor_lock(db):
    """add_new_metrics must be safe to call from another thread while writes
    are in progress on the same sensor.

    The writer only ever writes 1 column of data; the metric expansion to
    2 columns happens while the writer is stopped, so there is no
    'number of cols' mismatch. The test verifies that the lock prevents
    the writer from observing a half-rewritten chunk directory.
    """
    errors = []
    stop = threading.Event()

    def writer():
        try:
            for i in range(50):
                # sensor has 2 columns (m1, m2) from the db fixture
                db.write_tick_numpy(
                    WRITE,
                    "test",
                    "s1",
                    np.array([[float(i), float(i)]], dtype=DTYPE),
                    np_timestamps=np.array([_now() + i], dtype=np.float64),
                )
                if stop.is_set():
                    break
        except Exception as e:
            errors.append(e)

    t = threading.Thread(target=writer)
    t.start()
    time.sleep(0.02)
    stop.set()
    t.join()

    assert not errors, f"Errors during writes: {errors}"

    # Now extend metrics: it must complete cleanly.
    try:
        db.add_new_metrics(_admin(db), "test", "s1", ["m3"], fill_value=np.nan)
    except Exception as e:
        errors.append(("add_metrics", e))
    assert not errors, f"Errors: {errors}"

    metrics = db.get_metrics(READ, "test", "s1", force_reload=True)
    assert "m3" in metrics


def test_admin_key_not_in_logs(tmp_path, caplog):
    """E1: the auto-generated admin key must NOT appear in the log
    stream. It is printed to stdout as a one-time banner, but a
    capture of the log handlers (e.g. the default FileHandler) must
    not contain it.
    """
    import logging

    caplog.set_level(logging.INFO)
    # Bootstrap a fresh DB
    d = OngTSDB(path=str(tmp_path))
    with open(d.FU.path_config()) as f:
        admin = f.readline().strip()
    assert len(admin) >= 8  # sanity
    # The key must not appear in any log record
    assert admin not in caplog.text
    # The path to the config file IS logged (so it is recoverable)
    assert "DB correctly setup" in caplog.text


def test_check_auth_message_includes_action_name(db):
    """E6: the NotAuthorizedException raised by _check_auth must
    include the action name and the (db/sensor) target, so the
    user can tell at a glance which call failed and why.
    """
    from ong_tsdb.exceptions import NotAuthorizedException

    # Use a wrong key: db is configured for WRITE/READ keys; we send
    # neither, so the auth check must fail.
    with pytest.raises(NotAuthorizedException) as exc:
        db.write_tick_numpy(
            "definitely-not-the-write-key",
            "test",
            "s1",
            np.array([[1.0, 2.0]], dtype=DTYPE),
            np_timestamps=np.array([_now() + 1], dtype=np.float64),
        )
    msg = str(exc.value)
    assert "WRITE" in msg
    assert "test/s1" in msg


def test_parse_fill_value_warns_on_non_numeric():
    """E5: parse_fill_value must log a warning (not stay silent) when
    the input is not numeric. The default behaviour (return 0) is
    preserved.
    """
    from ong_tsdb.server import parse_fill_value

    with patch("ong_tsdb.server.logger") as mock_logger:
        result = parse_fill_value("not-a-number")
    assert result == 0
    mock_logger.warning.assert_called_once()
    # The warning must mention the bad value so the user can find the caller
    args = mock_logger.warning.call_args[0]
    assert "not-a-number" in args
